config-version: 2
name: 'twilio_source'

version: '0.1.0'
require-dbt-version: [">=1.3.0", "<2.0.0"]

models:
  twilio_source:
    +materialized: table
    +schema: stg_twilio
    tmp:
      +materialized: view
vars:
  twilio_source:
    : "{{ source('twilio', '') }}"
    : "{{ source('twilio', '') }}"
    : "{{ source('twilio', '') }}"
    : "{{ source('twilio', '') }}"
    : "{{ source('twilio', '') }}"
    : "{{ source('twilio', '') }}"
    : "{{ source('twilio', '') }}"
    : "{{ source('twilio', '') }}"
    : "{{ source('twilio', '') }}"
    : "{{ source('twilio', '') }}"
    : "{{ source('twilio', '') }}"
    : "{{ source('twilio', '') }}"
    : "{{ source('twilio', '') }}"
    : "{{ source('twilio', '') }}"
