config-version: 2
name: 'twilio_source_integration_tests'

version: '0.1.0'
profile: 'integration_tests'

vars:
  twilio_source:
    twilio_schema: twilio_source_integration_tests_1

seeds:
  twilio_source_integration_tests:
    +column_types:
      to: "{{ 'string' if target.name in ['bigquery','spark'] else 'varchar' }}"
      from: "{{ 'string' if target.name in ['bigquery','spark'] else 'varchar' }}"
    twilio_incoming_phone_number_data:
      phone_number: "{{ 'string' if target.name in ['bigquery','spark'] else 'varchar' }}"
    twilio_call_data:
      forwarded_from: "{{ 'string' if target.name in ['bigquery','spark'] else 'varchar' }}"
      from: "{{ 'string' if target.name in ['bigquery','spark'] else 'varchar' }}"
      to: "{{ 'string' if target.name in ['bigquery','spark'] else 'varchar' }}"
  