config-version: 2
name: 'twilio_source_integration_tests'

version: '0.1.0'
profile: 'integration_tests'

vars:
  twilio_source:
    twilio_schema: twilio_source_integration_tests_1

seeds:
  twilio_source_integration_tests:
    +column_types:
      to:
      from:
    twilio_incoming_phone_number_data:
      phone_number: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
    twilio_message_data:
      to: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
      from: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
    twilio_call_data:
      forwarded_from: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
      from: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
      to: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
  